[build]
  publish = "dist"
  command = "cd ../netlify/functions && npm install && cd ../../app/client && npx vite build --mode production"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@react-pdf/renderer", "canvas", "pdfkit"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200